//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab6
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RestaurantInfo", Namespace="http://schemas.datacontract.org/2004/07/Lab6")]
    public partial class RestaurantInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Lab6.Address LocationField;
        
        private string NameField;
        
        private int RatingField;
        
        private string SummaryField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Lab6.Address Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rating
        {
            get
            {
                return this.RatingField;
            }
            set
            {
                this.RatingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Summary
        {
            get
            {
                return this.SummaryField;
            }
            set
            {
                this.SummaryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/Lab6")]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CityField;
        
        private string PostalCodeField;
        
        private string ProvinceField;
        
        private string StreetField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province
        {
            get
            {
                return this.ProvinceField;
            }
            set
            {
                this.ProvinceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street
        {
            get
            {
                return this.StreetField;
            }
            set
            {
                this.StreetField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IRestaurantReviewService")]
public interface IRestaurantReviewService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantReviewService/GetRestaurantNames", ReplyAction="http://tempuri.org/IRestaurantReviewService/GetRestaurantNamesResponse")]
    string[] GetRestaurantNames();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantReviewService/GetRestaurantNames", ReplyAction="http://tempuri.org/IRestaurantReviewService/GetRestaurantNamesResponse")]
    System.Threading.Tasks.Task<string[]> GetRestaurantNamesAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantReviewService/GetRestaurantByName", ReplyAction="http://tempuri.org/IRestaurantReviewService/GetRestaurantByNameResponse")]
    Lab6.RestaurantInfo GetRestaurantByName(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantReviewService/GetRestaurantByName", ReplyAction="http://tempuri.org/IRestaurantReviewService/GetRestaurantByNameResponse")]
    System.Threading.Tasks.Task<Lab6.RestaurantInfo> GetRestaurantByNameAsync(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantReviewService/GetRestaurantsByRating", ReplyAction="http://tempuri.org/IRestaurantReviewService/GetRestaurantsByRatingResponse")]
    Lab6.RestaurantInfo[] GetRestaurantsByRating(int rating);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantReviewService/GetRestaurantsByRating", ReplyAction="http://tempuri.org/IRestaurantReviewService/GetRestaurantsByRatingResponse")]
    System.Threading.Tasks.Task<Lab6.RestaurantInfo[]> GetRestaurantsByRatingAsync(int rating);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantReviewService/SaveRestaurant", ReplyAction="http://tempuri.org/IRestaurantReviewService/SaveRestaurantResponse")]
    bool SaveRestaurant(Lab6.RestaurantInfo restInfo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantReviewService/SaveRestaurant", ReplyAction="http://tempuri.org/IRestaurantReviewService/SaveRestaurantResponse")]
    System.Threading.Tasks.Task<bool> SaveRestaurantAsync(Lab6.RestaurantInfo restInfo);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRestaurantReviewServiceChannel : IRestaurantReviewService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RestaurantReviewServiceClient : System.ServiceModel.ClientBase<IRestaurantReviewService>, IRestaurantReviewService
{
    
    public RestaurantReviewServiceClient()
    {
    }
    
    public RestaurantReviewServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RestaurantReviewServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RestaurantReviewServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RestaurantReviewServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string[] GetRestaurantNames()
    {
        return base.Channel.GetRestaurantNames();
    }
    
    public System.Threading.Tasks.Task<string[]> GetRestaurantNamesAsync()
    {
        return base.Channel.GetRestaurantNamesAsync();
    }
    
    public Lab6.RestaurantInfo GetRestaurantByName(string name)
    {
        return base.Channel.GetRestaurantByName(name);
    }
    
    public System.Threading.Tasks.Task<Lab6.RestaurantInfo> GetRestaurantByNameAsync(string name)
    {
        return base.Channel.GetRestaurantByNameAsync(name);
    }
    
    public Lab6.RestaurantInfo[] GetRestaurantsByRating(int rating)
    {
        return base.Channel.GetRestaurantsByRating(rating);
    }
    
    public System.Threading.Tasks.Task<Lab6.RestaurantInfo[]> GetRestaurantsByRatingAsync(int rating)
    {
        return base.Channel.GetRestaurantsByRatingAsync(rating);
    }
    
    public bool SaveRestaurant(Lab6.RestaurantInfo restInfo)
    {
        return base.Channel.SaveRestaurant(restInfo);
    }
    
    public System.Threading.Tasks.Task<bool> SaveRestaurantAsync(Lab6.RestaurantInfo restInfo)
    {
        return base.Channel.SaveRestaurantAsync(restInfo);
    }
}
